media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    format: yaml-frontmatter
    view:
      primary: title
      fields: [ title, date, image ]
      sort: [ date, title ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: post
        required: true

      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: image
        label: Featured image
        type: image
        required: false

      - name: body
        label: Body
        type: rich-text
        required: true

  - name: config
    label: Site settings
    type: file
    path: _config.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        type: string

      - name: email
        label: Email
        type: string

      - name: timezone
        label: Timezone
        type: string

      - name: url
        label: Site URL
        type: string

      - name: baseurl
        label: Base URL
        type: string

      - name: logo
        label: Logo
        type: image

      - name: favicon
        label: Favicon
        type: image

      - name: paginate
        label: Posts per page
        type: number

      - name: disqus
        label: Disqus shortname
        type: string

      - name: lang
        label: Language
        type: string

      - name: locale
        label: Locale
        type: string
