media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string

      - name: date
        label: Date
        type: date

      - name: hero_image
        label: Hero Image
        type: image

      - name: hero_alt
        label: Hero Image Alt Text
        type: string

      - name: hero_caption
        label: Hero Caption
        type: string

      - name: body
        label: Content
        type: rich-text

  - name: about
    label: About
    type: file
    path: about/index.html
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string

      - name: permalink
        label: Permalink
        type: string
        required: false

      - name: body
        label: Content
        type: rich-text
