title: Moini
description: Urban planning, GIS, and projects.
url: https://moini.org
baseurl: ""
timezone: America/Toronto

markdown: kramdown
future: false

# Keep post URLs short like /blog/my-post/
permalink: /blog/:slug/

collections:
  posts:
    output: true
  redirects:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
