title: Moini
description: Urban planning, GIS, and projects.
url: https://moini.org
baseurl: ""
timezone: America/Toronto
linkedin_url: "https://www.linkedin.com/in/kouroshmoini/"

markdown: kramdown
future: false

# Keep post URLs like /2026/01/29/title/
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
